language: php
before_script:
- composer global require justinwalsh/daux.io
script:
- "~/.composer/vendor/bin/daux"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: static
  on:
    branch: master
